### ISSUE TITLE
Accepting JSON Arrays as input parameters. 

### ISSUE THREAD

**Issue by barik-jyoti** [dotnetjunkie/solidservices#22]
Hi, 

I have a situation where for the command contract, in one of the parameters I would like to accept JSON Array. 

``` json
Command Contract 
{
  "clientId": 309,
  "jsonKey": 1,
  "functionalKey": 2,
  "leaseData": ""
}
```

In leaseData field I need to accept a JSON array like below -

``` json
[{"EffectiveDate":"1/2/2015",
    "EndingDate":"1/3/2017","GIA":"1","GIAMeasure":"Ping","NIA":"1",
    "NIAMeasure":"Ping","TenureName":"Red Run 1",
    "TenureId":"MD-OWM-004","AreaType":"Archive","Comments":"Test","Vacant":"Yes"
}]
```
How can this be handled. Please suggest. 

Thanks, 
JPB

**Comment by dotnetjunkie** [comment]
I have no idea. Can you describe what it is you want to achieve?
