### ISSUE TITLE
how to handle massive queries

### ISSUE THREAD

**Issue by maulwuff** [dotnetjunkie/solidservices#23]
I am in the situation where I have to create a kind of dynamic query with loads and loads of optional cols/properties. These are cols to add to a data export. Assume some 1000 cols are possible. But also only 1 col - just how the user is about to configure the export. These cols are sourced somewhere in lots of different tables which need to get joined.
 So definetly not something for hard coded query classes. :(

what I came up with is this use case:
- enable query results with variable columns in its result set
- messages should be typed and not be strings

```csharp

class TableA {
    string A1 {get;set;}
    string A2 {get;set;}
}

class TableB {
    string B1 {get;set;}
    string B2 {get;set;}
}

class TableC {
    string C1 {get;set;}
    string C2 {get;set;}
}

//some kind of multilevel tree to handle the loads of options
class AllCols {
    TableA A {get;set;}
    TableB B {get;set;}
    TableC C {get;set;}
}

class GetColsQuery<AllCols> {
    //maybe some filter
}

class GetReportResult<Report> {
    //like: "get report with cols A.A1, B.B2, C.C1"

    //with strings 
    List<string> ColsForReport {get;set;} //<- filled with nameof()-style helper

   // with dummy tree-object  
    AllCols ColsForReport {get;set;} //<- all fields to include are set to not-null 
   
   //with json:  build a json object and parse it back onto a full object with 
    jsonNet.populateObject or jObject.ToObject<TableA>()
}

class Report {
    //some result stuff
}
```

- with `List<string>`: it's a string list. not typesafe
- with dummy tree-object: maybe? dummy values feel rather smelly
- with json: json.net has the possibility to populate objects from an incomplete json representation. 
    json is the language of webApi, but before and after webApi its just strings - like above.
    
Do you have any other idea on how to solve this?

**Comment by dotnetjunkie** [comment]
This seems like something you would do using [Dynamic LINQ](https://weblogs.asp.net/scottgu/dynamic-linq-part-1-using-the-linq-dynamic-query-library) ([nuget](https://www.nuget.org/packages/System.Linq.Dynamic/))

This allows you to create a complete dynamic approach where you send the column names over via strings, or you can still use a typed DTO and use reflection to map them to the LINQ query dynamically based on their availability.

**Comment by maulwuff** [comment]
after inspecting swagger, we stick with strongly typed DTOs, built up like shown above in `AllCols`.
everything else just shows up as string field, with no help what can be entered as valid value.
