### ISSUE TITLE
Failed

### ISSUE THREAD

**Issue by PeterJD** [dotnetjunkie/solidservices#27]
Enjoyed viewing solidservices, but i judge a book by its cover, or if the app runs ok investigate unfortunately
I was unable to successfully run app, always times out?

Any suggestion?

Well I did learn something, I was a amazed to see you implement System.Data.Entity

Coding style is clean, a solution would be nice so I can investigate your code more

Always prove the code works 

Peter

**Comment by dotnetjunkie** [comment]
The master branch unfortunately had a compile error, caused by the latest merge. I fixed this, but after that the solution runs successfully on my machine. I tested this by starting the `WcfService` project and after that starting the `Client` project. Result is the following output:

![afbeelding](https://user-images.githubusercontent.com/1506621/54085126-51242c00-433a-11e9-94a2-94940ba929f9.png)

Can you provide additional information on what you tried, and the details of the exception that happens on time out?

**Comment by PeterJD** [comment]
Hi StevenThanks for the info, that in part seem to work, but your Wcfservice doesn't provide out like (please see attach files)
Kind regardsPeter    On Sunday, 10 March 2019, 12:43:48 GMT, Steven <notifications@github.com> wrote:  
 
 
The master branch unfortunately had a compile error, caused by the latest merge. I fixed this, but after that the solution runs successfully on my machine. I tested this by starting the WcfService project and after that starting the Client project. Result is the following output:



Can you provide additional information on what you tried, and the details of the exception that happens on time out?

**Comment by dotnetjunkie** [comment]
Hi Peter,

You can't reply to GitHub notifications using mail attachments. Can you please post the relevant information to allow me review and analyze your issue directly here on GitHub?

**Comment by PeterJD** [comment]
[localhost - _.pdf](https://github.com/dotnetjunkie/solidservices/files/2949617/localhost.-._.pdf)
[PersonWcfService Service.pdf](https://github.com/dotnetjunkie/solidservices/files/2949618/PersonWcfService.Service.pdf)

**Comment by PeterJD** [comment]
Secondly I use a tool from Microsoft which allows me to test WCF
WCF Test, For some reason on your app isnot invoke any idea why?
![Test WCF](https://user-images.githubusercontent.com/5926879/54087305-7d937480-4349-11e9-9b53-68324648f3a8.png)

**Comment by dotnetjunkie** [comment]
Great. It seems you was able to start the WCF service using Visual Studio.

The information you posted, however, shows an additional `PersonService` that you have added. This, to me, is an indication that you don't understand the model that this reference application is built around.

Please make yourself familiar with this model by reading the blog posts that the [README.MD](https://github.com/dotnetjunkie/solidservices/blob/master/README.md) links to before continuing with your review of this code base.

Also note that the default WCF test client only understands simple method invocations, where with this model, there is only one method that accept a large set of input messages. You might get this to work with that client, but I never bothered trying. Instead, you can use a simple console application (such as the provided `Client` project), or even interactive scripting environment to test your WCF service.

**Comment by PeterJD** [comment]
Hi StevenWill read the info, but personservice was from a different project just wanted to indicate to you I was unable to load your services to the web.
Your service error :-
With HTTP Error 403.14  ForbiddenThe web server is configured to not list the contents of this directory
Kind regards
Peter

    On Sunday, 10 March 2019, 15:37:08 GMT, Steven <notifications@github.com> wrote:  
 
 
Great. It seems you was able to start the WCF service using Visual Studio.

The information you posted, however, shows an additional PersonService that you have added. This, to me, is an indication that you don't understand the model that this reference application is built around.

Please make yourself familiar with this model by reading the blog posts that the README.MD links to before continuing with your review of this code base.

Also note that the default WCF test client only understands simple method invocations, where with this model, there is only one method that accept a large set of input messages. You might get this to work with that client, but I never bothered trying. Instead, you can use a simple console application (such as the provided Client project), or even interactive scripting environment to test your WCF service.
