### ISSUE TITLE
ASP.NET core sample throws exception because of missing IHttpContextAccessor registration

### ISSUE THREAD

**Issue by devhb** [dotnetjunkie/solidservices#29]
While playing around with SimpleInjector and the sample for ASP.Core I found that the sample is not working in it's current state.

When running the sample for ASP.NET Core the following exception is thrown
```
System.InvalidOperationException
  HResult=0x80131509
  Message=The configuration is invalid. Creating the instance for type ICommandHandler<CreateOrderCommand> failed. The constructor of type Bootstrapper.HttpContextPrincipal contains the parameter with name 'httpContextAccessor' and type IHttpContextAccessor that is not registered. Please ensure IHttpContextAccessor is registered, or change the constructor of Bootstrapper.HttpContextPrincipal.
  Source=SimpleInjector
  StackTrace:
   at SimpleInjector.InstanceProducer.VerifyExpressionBuilding()
   at SimpleInjector.Container.VerifyThatAllExpressionsCanBeBuilt(InstanceProducer[] producersToVerify)
   at SimpleInjector.Container.VerifyThatAllExpressionsCanBeBuilt()
   at SimpleInjector.Container.VerifyInternal(Boolean suppressLifestyleMismatchVerification)
   at SimpleInjector.Container.Verify()
   at WebCoreService.Bootstrapper.Bootstrap(Container container, IApplicationBuilder app) in C:\Users\klaas.hoffmann\Source\Repos\solidservices\src\WebCoreService\Bootstrapper.cs:line 29
   at WebCoreService.Startup.Configure(IApplicationBuilder app, IHostingEnvironment env) in C:\Users\klaas.hoffmann\Source\Repos\solidservices\src\WebCoreService\Startup.cs:line 55

Inner Exception 1:
ActivationException: The constructor of type Bootstrapper.HttpContextPrincipal contains the parameter with name 'httpContextAccessor' and type IHttpContextAccessor that is not registered. Please ensure IHttpContextAccessor is registered, or change the constructor of Bootstrapper.HttpContextPrincipal.
```
According to the great documentation I found that a call to `container.AutoCrossWireAspNetComponents` is missing.

I have changed the sample and try to make a pull request.

It's again time to say "thank you Steven (and the team) for your brilliant work regarding SimpleInjector (including the documentation!)".
I've worked with many DI container, but no other product is as good as the one you created.
I don't know how often I've had a look in the documentation (and now your book too) to do things in the right way.

**Comment by devhb** [comment]
I tries to make a pull request, but I get

> Remote: Permission to dotnetjunkie/solidservices.git denied to devhb.
Error encountered while pushing to the remote repository: Git failed with a fatal error.
unable to access 'https://github.com/dotnetjunkie/solidservices/': The requested URL returned error: 403

My fix was to add the comment and the `AutoCrossWireAspNetComponents `call, so the `Configure` method looks like

```
// This method gets called by the runtime. Use this method to configure the HTTP request pipeline.
public void Configure(IApplicationBuilder app, IHostingEnvironment env)
{
   // Allow Simple Injector to resolve services from ASP.NET Core.
   this.container.AutoCrossWireAspNetComponents(app);

   Bootstrapper.Bootstrap(this.container, app);

}
```

**Comment by dotnetjunkie** [comment]
I'm sorry. It seemed that the pull request for the ASP.NET Core project, which I accepted earlier, was a work-in-progress solution. I'm also unsure why you are getting that GIT error.

However, I just pushed a fix to the ASP.NET Core project. I needed to do quite some changes to get it running. Do note, however, that the quality of this project is lower than the Web API project. I and others already used the Web API project successfully as a template for projects that now run in production. The ASP.NET Core project, likely, requires some more tuning, for instance to support other content types. So be warned. Feedback is obviously welcome.

**Comment by devhb** [comment]
I'm aware of the fact that the ASP.NET Core project is in an early stage but served as a good starting point for me to wire my old service layer (WCF) with the core DI things.

I will proceed with the migration and give feedback if I found other things.

Will close this issue as it seems it's resolved now. 
Thanks for taking the time!
